services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/html/public
    depends_on:
      - pgadmin
  react:
    hostname: react
    build: frontend
    volumes:
      - ./frontend:/root/tagnotes_react
  fpm:
    build: backend
    hostname: fpm
    volumes:
      - ./backend:/var/www/html:cached
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      migration:
        condition: service_completed_successfully
    extra_hosts:
      - "host.docker.internal:host-gateway"
