services:
  nginx:
    image: nginx:latest
    container_name: tagnotes_nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/html/public
    links:
      - fpm
      - react
  fpm:
    build: backend
    container_name: tagnotes_fpm
    volumes:
      - ./backend:/var/www/html
    links:
      - postgres
  postgres:
    image: postgres:latest
    container_name: tagnotes_postgres
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  react:
    build: frontend
    container_name: tagnotes_react
    volumes:
      - ./frontend:/root/tagnotes_react

