services:
  nginx:
    image: nginx:latest
    container_name: tagnotes_nginx
    ports:
      - "80:80"
    volumes:
      - ./app/files/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/src:/var/www/html
    links:
      - fpm
  fpm:
    build: ./app
    container_name: tagnotes_fpm
    volumes:
      - ./app/src:/var/www/html
    links:
      - postgres
  postgres:
    image: postgres:latest
    container_name: tagnotes_postgres
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
