lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # 1 hour
    allow_no_expiration: false
    api_platform:
        check_path: /api/login_check
        username_path: name
        password_path: security.credentials

    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        split_cookie:
            enabled: true
            cookies:
                - jwt_hp
                - jwt_s

    set_cookies:
        jwt_hp:
            lifetime: null
            samesite: strict
            path: /
            domain: null
            httpOnly: false
            secure: false
            partitioned: false
            split:
                - header
                - payload
        jwt_s:
            lifetime: 0
            samesite: strict
            path: /
            domain: null
            httpOnly: true
            secure: false
            partitioned: false
            split:
                - signature

    remove_token_from_body_when_cookies_used: true
